### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by SensorsIot** [duff2013/ulptool#59]
File 
I installed the tools according to your instructions and use python 3.8. I get this error:

"C:\Users\andre\AppData\Local\Arduino15\packages\esp32\tools\ulptool\src/esp32ulp_build_recipe.py", line 305

    print e

          ^

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(e)?

**Comment by SensorsIot** [comment]
I tried it by changing the path to version 2.7 and it compiled...

**Comment by swaraj429** [comment]
where to change path?

**Comment by hanshuettmann** [comment]
Hi! I get the same error but I don't know where to change the path to the version you said. Would you help me?

**Comment by swaraj429** [comment]
i was unable to find the way
so i switched  to linux with only py 2.7 installed
